//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to process a received chat join request query. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub AnswerChatJoinRequestQuery (AnswerChatJoinRequestQuerySetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// Result of the query. Must be either "approve" to allow the user to join the chat, "decline" to disallow the user to join the chat, or "queue" to leave the decision to other administrators.
            pub result: String [into],
        }
    }
}
