//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{MessageId, Recipient, True, UserId};

impl_payload! {
    /// Use this method to delete an ephemeral message. Note that it is not guaranteed that the user will receive the message deletion event, especially if they are offline. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteEphemeralMessage (DeleteEphemeralMessageSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup in the format `@username`
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to delete
            #[serde(flatten)]
            pub ephemeral_message_id: MessageId,
        }
    }
}
