//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, MessageId, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit only the reply markup of an ephemeral message. Note that it is not guaranteed that the user will receive the message edit event, especially if they are offline. On success, True is returned.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageReplyMarkup (EditEphemeralMessageReplyMarkupSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup in the format `@username`
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            #[serde(flatten)]
            pub ephemeral_message_id: MessageId,
        }
        optional {
            /// A JSON-serialized object for an inline keyboard
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
