//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{
    InlineKeyboardMarkup, MessageEntity, MessageId, ParseMode, Recipient, True, UserId,
};

impl_payload! {
    /// Use this method to edit the caption of an ephemeral message. Note that it is not guaranteed that the user will receive the message edit event, especially if they are offline. On success, True is returned.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageCaption (EditEphemeralMessageCaptionSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup in the format `@username`
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            #[serde(flatten)]
            pub ephemeral_message_id: MessageId,
        }
        optional {
            /// New caption of the message, 0-1024 characters after entities parsing
            pub caption: String [into],
            /// Mode for parsing entities in the message caption. See [formatting options] for more details.
            ///
            /// [formatting options]: https://core.telegram.org/bots/api#formatting-options
            pub parse_mode: ParseMode,
            /// A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
            pub caption_entities: Vec<MessageEntity> [collect],
            /// Pass True if the caption must be shown above the message media. Supported only for animation, photo and video messages.
            pub show_caption_above_media: bool,
            /// A JSON-serialized object for an inline keyboard
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
