//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{KeyboardButton, PreparedKeyboardButton, UserId};

impl_payload! {
    /// Use this method to store a keyboard button to be used by the user of a Mini App. Returns a [`PreparedKeyboardButton`] on success.
    ///
    /// [`PreparedKeyboardButton`]: crate::types::PreparedKeyboardButton
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SavePreparedKeyboardButton (SavePreparedKeyboardButtonSetters) => PreparedKeyboardButton {
        required {
            /// Unique identifier of the target user
            pub user_id: UserId,
            /// A JSON-serialized object with the description of the button
            pub button: KeyboardButton,
        }
    }
}
