//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to process a received chat join request query by showing a Mini App to the user before deciding the outcome. Call [`AnswerChatJoinRequestQuery`] to resolve the join request query based on the user interaction with the Mini App. Returns _True_ on success.
    ///
    /// [`AnswerChatJoinRequestQuery`]: crate::payloads::AnswerChatJoinRequestQuery
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendChatJoinRequestWebApp (SendChatJoinRequestWebAppSetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// The URL of the Mini App to be opened
            pub web_app_url: String [into],
        }
    }
}
