//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{DraftId, InputRichMessage, Recipient, ThreadId, True};

impl_payload! {
    /// Use this method to stream a partial rich message to a user while the message is being generated. Returns _True_ on success.
    #[derive(Debug, PartialEq, Clone, Serialize)]
    pub SendRichMessageDraft (SendRichMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: Recipient [into],
            /// Unique identifier of the message draft; must be non-zero
            pub draft_id: DraftId,
            /// The partial message to be streamed
            pub rich_message: InputRichMessage,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
        }
    }
}
